BOOLEAN VECTORS AND MATRICES

In [2]:
import numpy as np
vector = np.array([True,False,True,False])
matrix  = vector.reshape(2,-1)
matrix

array([[ True, False],
       [ True, False]])

In [3]:
matrix = np.arange(10).reshape(2,5)
matrix

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
matrix<5

array([[ True,  True,  True,  True,  True],
       [False, False, False, False, False]])